NDefines.NGame.START_DATE = "1970.1.1.12";
NDefines.NGame.END_DATE = "1999.1.1.1";
NDefines.NGame.MISSION_REMOVE_FROM_INTERFACE_DEFAULT = 0;
NDefines.NDiplomacy.MAX_TRUST_VALUE = 200;
NDefines.NDiplomacy.MIN_TRUST_VALUE = -500;
NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION = 0.5;
NDefines.NDiplomacy.TENSION_TIME_SCALE_START_DATE = "1970.1.1.12";	-- Starting at this date, the tension values will be scaled down (will be equal to 1 before that)
NDefines.NDiplomacy.TENSION_TIME_SCALE_MONTHLY_FACTOR = -0.005;
NDefines.NCountry.BASE_MAX_COMMAND_POWER = 1000.0;
NDefines.NCountry.SPECIAL_FORCES_CAP_BASE = 0.05;
NDefines.NCountry.SPECIAL_FORCES_CAP_MIN = 24;
NDefines.NBuildings.MAX_BUILDING_LEVELS = 72;
NDefines.NBuildings.MAX_SHARED_SLOTS = 72;
NDefines.NMilitary.MAX_ARMY_EXPERIENCE = 999;
NDefines.NMilitary.MAX_NAVY_EXPERIENCE = 999;
NDefines.NMilitary.MAX_AIR_EXPERIENCE = 999;
NDefines.NMilitary.ENCIRCLED_DISBAND_MANPOWER_FACTOR = 0.05;
NDefines.NMilitary.FIELD_EXPERIENCE_SCALE = 0.015;
NDefines.NMilitary.FIELD_EXPERIENCE_MAX_PER_DAY = 25;
NDefines.NMilitary.EXPEDITIONARY_FIELD_EXPERIENCE_SCALE = 0.15;
NDefines.NMilitary.MIN_DIVISION_DEPLOYMENT_TRAINING = 0.3;
NDefines.NAir.FIELD_EXPERIENCE_SCALE = 0.01;
NDefines.NAir.FIELD_EXPERIENCE_MAX_PER_DAY = 20;
NDefines.NNavy.FIELD_EXPERIENCE_SCALE = 0.75;
NDefines.NNavy.FIELD_EXPERIENCE_MAX_PER_DAY = 100;
NDefines.NNavy.CARRIER_STACK_PENALTY = 6;


